name: Vitest Unit Test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Vite
      run: npm i vite
    - name: Install Vitest
      run: npm i vitest
    - name: Run Unit test
      run: npm run test
    - uses: actions/upload-artifact@v2
      if: always()
      name: vitest-report
        path: vitest-report/
        retention-days: 30
     
